version: "3"

services:
  profana:
    container_name: profana
    build:
      context: ..
    ports:
      - 3000:3000
      - 9090:9090
  
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./:/usr/share/nginx/html
